import { buildEffectTokens } from './effectTokens.js';
import { clamp, round } from './number.js';

const formatOpacity = (value) => round(clamp(value, 0, 1), 2);

const formatCssShadow = (shadow) => shadow.replace(/\s{2,}/g, ' ').trim();

const templateHeader = (title) => `/* ${title} */\n`;

const baseMarkup = (
  className,
  framework,
) => (framework === 'react'
  ? `export function GlassCard() {\n  return (\n    <article className="${className}">\n      <header className="glass-card__header">\n        <div className="glass-card__avatar">\n          <span>JD</span>\n        </div>\n        <div>\n          <p className="glass-card__eyebrow">Product Designer</p>\n          <h3 className="glass-card__title">Juno Doe</h3>\n        </div>\n      </header>\n      <p className="glass-card__body">Design soft, luminous surfaces using liquid glass tokens generated by the playground.</p>\n      <button className="glass-card__cta">Get started</button>\n    </article>\n  );\n}`
  : `<article class="${className}">\n  <header class="glass-card__header">\n    <div class="glass-card__avatar">\n      <span>JD</span>\n    </div>\n    <div>\n      <p class="glass-card__eyebrow">Product Designer</p>\n      <h3 class="glass-card__title">Juno Doe</h3>\n    </div>\n  </header>\n  <p class="glass-card__body">Design soft, luminous surfaces using liquid glass tokens generated by the playground.</p>\n  <button class="glass-card__cta">Get started</button>\n</article>`);

const nativeCss = (tokens) => {
  const borderRule = tokens.borderWidth > 0
    ? `border: ${tokens.borderWidth}px solid rgba(255, 255, 255, ${formatOpacity(tokens.borderOpacity)});`
    : 'border: 1px solid rgba(255, 255, 255, 0.06);';

  const highlightPseudo = `  content: '';\n  position: absolute;\n  inset: -25%;\n  background: radial-gradient(circle at 30% 20%, ${tokens.highlightColor}, transparent ${tokens.highlightSize});\n  filter: blur(${tokens.highlightBlur});\n  opacity: ${formatOpacity(tokens.shadowOpacity + 0.25)};\n  mix-blend-mode: screen;`;

  const noisePseudo = `  content: '';\n  position: absolute;\n  inset: 0;\n  opacity: ${formatOpacity(tokens.noiseOpacity)};\n  background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><filter id="n"><feTurbulence type="fractalNoise" baseFrequency="0.9" numOctaves="3"/></filter><rect width="40" height="40" filter="url(%23n)" opacity="0.55"/></svg>');\n  mix-blend-mode: soft-light;`;

  const css = `${templateHeader('Glass Card styles')}.glass-card {\n  position: relative;\n  overflow: hidden;\n  border-radius: ${tokens.borderRadius}px;\n  ${borderRule}\n  background: ${tokens.gradient};\n  backdrop-filter: blur(${tokens.blur}px) saturate(${tokens.saturation}%) brightness(${tokens.brightness}%);\n  box-shadow: ${formatCssShadow(tokens.cardShadow)};\n  color: rgba(226, 232, 240, 0.95);\n}\n\n.glass-card::before {\n${highlightPseudo}\n}\n\n.glass-card::after {\n${noisePseudo}\n}\n\n.glass-card__header {\n  display: flex;\n  align-items: center;\n  gap: 1rem;\n}\n\n.glass-card__avatar {\n  display: inline-flex;\n  align-items: center;\n  justify-content: center;\n  width: 3rem;\n  height: 3rem;\n  border-radius: 999px;\n  background: radial-gradient(circle at 30% 30%, rgba(255, 255, 255, 0.3), rgba(148, 163, 184, 0.12));\n  font-weight: 600;\n  letter-spacing: 0.08em;\n}\n\n.glass-card__eyebrow {\n  margin: 0;\n  font-size: 0.8rem;\n  text-transform: uppercase;\n  letter-spacing: 0.28em;\n  opacity: 0.7;\n}\n\n.glass-card__title {\n  margin: 0.2rem 0 0;\n  font-size: 1.5rem;\n  font-weight: 600;\n}\n\n.glass-card__body {\n  margin: 1rem 0 1.5rem;\n  font-size: 0.95rem;\n  line-height: 1.6;\n  color: rgba(226, 232, 240, 0.85);\n}\n\n.glass-card__cta {\n  display: inline-flex;\n  align-items: center;\n  justify-content: center;\n  padding: 0.75rem 1.8rem;\n  border-radius: 999px;\n  background: linear-gradient(135deg, ${tokens.highlightColor}, ${tokens.highlightRim});\n  color: #0f172a;\n  border: none;\n  font-weight: 600;\n  letter-spacing: 0.05em;\n  cursor: pointer;\n  transition: transform 180ms ease, opacity 180ms ease;\n}\n\n.glass-card__cta:hover {\n  transform: translateY(-1px);\n  opacity: 0.95;\n}`;

  return css;
};

const tailwindMarkup = (tokens, framework) => {
  const wrapperClasses = [
    'relative isolate overflow-hidden',
    `rounded-[${tokens.borderRadius}px]`,
    'px-8 py-10',
    `backdrop-blur-[${tokens.blur}px]`,
    `saturate-[${tokens.saturation}%]`,
    `brightness-[${tokens.brightness}%]`,
    tokens.borderWidth > 0
      ? `ring-1 ring-[rgba(255,255,255,${formatOpacity(tokens.borderOpacity)})]`
      : 'ring-1 ring-white/10',
    `bg-[${tokens.gradient.replace(/\s/g, '_')}]`,
    `shadow-[${tokens.cardShadow.replace(/\s/g, '_')}]`,
  ].join(' ');

  const glowClasses = [
    'pointer-events-none',
    'absolute',
    'inset-0',
    `opacity-[${formatOpacity(tokens.shadowOpacity + 0.25)}]`,
    'mix-blend-screen',
    `bg-[radial-gradient(circle_at_30%_20%,${tokens.highlightColor.replace(/\s/g, '_')},transparent_${tokens.highlightSize})]`,
    `blur-[${Math.round(tokens.highlightSpread * 0.85)}px]`,
  ].join(' ');

  const markup = framework === 'react'
    ? `export function GlassCard() {\n  return (\n    <article className="${wrapperClasses}">\n      <div className="${glowClasses}" />\n      <div className="relative flex flex-col gap-6">\n        <header className="flex items-center gap-4">\n          <div className="flex h-12 w-12 items-center justify-center rounded-full bg-white/15 text-sm font-semibold tracking-[0.3em]">JD</div>\n          <div>\n            <p className="text-xs uppercase tracking-[0.3em] text-slate-200/70">Product Designer</p>\n            <h3 className="mt-1 text-2xl font-semibold text-slate-100">Juno Doe</h3>\n          </div>\n        </header>\n        <p className="text-sm leading-relaxed text-slate-200/80">Design soft, luminous surfaces using liquid glass tokens generated by the playground.</p>\n        <button className="inline-flex w-max items-center justify-center rounded-full bg-gradient-to-br from-white/90 to-white/60 px-6 py-3 text-sm font-semibold uppercase tracking-[0.2em] text-slate-900 transition hover:brightness-110">Get started</button>\n      </div>\n    </article>\n  );\n}`
    : `<article class="${wrapperClasses}">\n  <div class="${glowClasses}"></div>\n  <div class="relative flex flex-col gap-6">\n    <header class="flex items-center gap-4">\n      <div class="flex h-12 w-12 items-center justify-center rounded-full bg-white/15 text-sm font-semibold tracking-[0.3em]">JD</div>\n      <div>\n        <p class="text-xs uppercase tracking-[0.3em] text-slate-200/70">Product Designer</p>\n        <h3 class="mt-1 text-2xl font-semibold text-slate-100">Juno Doe</h3>\n      </div>\n    </header>\n    <p class="text-sm leading-relaxed text-slate-200/80">Design soft, luminous surfaces using liquid glass tokens generated by the playground.</p>\n    <button class="inline-flex w-max items-center justify-center rounded-full bg-gradient-to-br from-white/90 to-white/60 px-6 py-3 text-sm font-semibold uppercase tracking-[0.2em] text-slate-900 transition hover:brightness-110">Get started</button>\n  </div>\n</article>`;

  const tailwindNotes = `// tailwind.config.js\nexport default {\n  content: ['./src/**/*.{js,jsx,ts,tsx,html}'],\n  theme: {\n    extend: {},\n  },\n  plugins: [],\n};`;

  return { markup, tailwindNotes };
};

export function generateNativeSnippet(settings, framework) {
  const tokens = buildEffectTokens(settings);
  const markup = baseMarkup('glass-card', framework);
  const styles = nativeCss(tokens);
  return { markup, styles };
}

export function generateTailwindSnippet(settings, framework) {
  const tokens = buildEffectTokens(settings);
  return tailwindMarkup(tokens, framework);
}

export function generateSnippet(settings, { syntax = 'native', framework = 'react' } = {}) {
  if (syntax === 'tailwind') {
    return generateTailwindSnippet(settings, framework);
  }
  return generateNativeSnippet(settings, framework);
}
