export const EFFECT_TYPES = {
  liquid: {
    label: 'Liquid Glass',
    description: 'Hyper-saturated, dreamy specular reflections that feel fluid and futuristic.',
  },
  glass: {
    label: 'Glassmorphism',
    description: 'Frosted panels with sharp highlights and layered depth using blur and gradients.',
  },
  neomorphic: {
    label: 'Neumorphism',
    description: 'Softly extruded surfaces with diffused shadows and subtle depth cues.',
  },
};

export const PRESETS = [
  {
    id: 'liquid-crystal',
    name: 'Liquid Crystal',
    effectType: 'liquid',
    settings: {
      blur: 48,
      saturation: 175,
      brightness: 120,
      borderRadius: 24,
      borderWidth: 1,
      borderOpacity: 0.45,
      backgroundAngle: 130,
      backgroundIntensity: 65,
      highlightHue: 265,
      highlightIntensity: 65,
      highlightSpread: 52,
      shadowOpacity: 0.28,
      noise: 0.15,
    },
  },
  {
    id: 'neo-glow',
    name: 'Neo Glow',
    effectType: 'neomorphic',
    settings: {
      blur: 32,
      saturation: 115,
      brightness: 112,
      borderRadius: 28,
      borderWidth: 0,
      borderOpacity: 0,
      backgroundAngle: 45,
      backgroundIntensity: 35,
      highlightHue: 210,
      highlightIntensity: 45,
      highlightSpread: 40,
      shadowOpacity: 0.22,
      noise: 0.08,
    },
  },
  {
    id: 'misty-drop',
    name: 'Misty Drop',
    effectType: 'glass',
    settings: {
      blur: 36,
      saturation: 135,
      brightness: 118,
      borderRadius: 18,
      borderWidth: 1,
      borderOpacity: 0.55,
      backgroundAngle: 160,
      backgroundIntensity: 45,
      highlightHue: 320,
      highlightIntensity: 38,
      highlightSpread: 46,
      shadowOpacity: 0.32,
      noise: 0.1,
    },
  },
  {
    id: 'mercury-drop',
    name: 'Mercury Drop',
    effectType: 'liquid',
    settings: {
      blur: 52,
      saturation: 145,
      brightness: 130,
      borderRadius: 40,
      borderWidth: 2,
      borderOpacity: 0.5,
      backgroundAngle: 110,
      backgroundIntensity: 75,
      highlightHue: 195,
      highlightIntensity: 55,
      highlightSpread: 58,
      shadowOpacity: 0.35,
      noise: 0.2,
    },
  },
  {
    id: 'velvet-noir',
    name: 'Velvet Noir',
    effectType: 'neomorphic',
    settings: {
      blur: 28,
      saturation: 105,
      brightness: 102,
      borderRadius: 32,
      borderWidth: 0,
      borderOpacity: 0,
      backgroundAngle: 35,
      backgroundIntensity: 32,
      highlightHue: 250,
      highlightIntensity: 30,
      highlightSpread: 30,
      shadowOpacity: 0.26,
      noise: 0.05,
    },
  },
  {
    id: 'ocean-wave',
    name: 'Ocean Wave',
    effectType: 'glass',
    settings: {
      blur: 42,
      saturation: 155,
      brightness: 118,
      borderRadius: 22,
      borderWidth: 1,
      borderOpacity: 0.52,
      backgroundAngle: 200,
      backgroundIntensity: 55,
      highlightHue: 210,
      highlightIntensity: 52,
      highlightSpread: 48,
      shadowOpacity: 0.27,
      noise: 0.12,
    },
  },
];

export const DEFAULT_SETTINGS = {
  effectType: 'liquid',
  blur: 48,
  saturation: 165,
  brightness: 120,
  borderRadius: 24,
  borderWidth: 1,
  borderOpacity: 0.5,
  backgroundAngle: 130,
  backgroundIntensity: 65,
  highlightHue: 260,
  highlightIntensity: 60,
  highlightSpread: 50,
  shadowOpacity: 0.3,
  noise: 0.12,
};
